name: Release

on:
  push:
    tags: [ "v*" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: cargo test --locked --lib
      - name: Build
        run: cargo build --locked --release
      - name: Publish
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create "$env:GITHUB_REF_NAME" target/release/wayfinder.exe --title "Wayfinder $env:GITHUB_REF_NAME" --generate-notes
